services:
  db:
    image: postgres:15
    container_name: don_charo
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: don_charo
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - don_charo_network

  backend:
    build: ./backend
    container_name: don_charo_backend
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    environment:
      DATABASE_URL: postgresql://postgres:1234@db:5432/don_charo
    depends_on:
      - db
    volumes:
      - ./backend:/app
    networks:
      - don_charo_network

  frontend:
    build: ./frontend
    container_name: don_charo_frontend
    ports:
      - "3000:3000"
    environment:
      - REACT_APP_API_URL=http://localhost:8000
    depends_on:
      - backend
    volumes:
      - ./frontend:/app
      - /app/node_modules
    networks:
      - don_charo_network

volumes:
  postgres_data:

networks:
  don_charo_network:
    driver: bridge